development:
  sessions:
    default:
      database: facebook_dev 
      hosts:
        - localhost:27017 
test:
  sessions:
    default:
      database: facebook_test
      hosts:
        - localhost:27017 
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
